% surgical_rules.pl
% SurgicalWiki Pro - General Surgery Knowledge Base
% SWI-Prolog 9.x | ASCII only | auto-generated by generate_surgical_rules.py

:- discontiguous protect_structure/2.
:- discontiguous must_precede/3.
:- discontiguous complication_risk/3.
:- discontiguous drain_indicated/1.
:- discontiguous drain_mandatory/1.


protect_structure(bile_duct, cholecystectomy).

protect_structure(common_bile_duct, cholecystectomy).

protect_structure(common_bile_duct, hepatectomy).

protect_structure(cystic_artery, cholecystectomy).

protect_structure(right_hepatic_artery, cholecystectomy).

protect_structure(portal_vein, hepatectomy).

protect_structure(portal_vein, pancreaticoduodenectomy).

protect_structure(hepatic_artery, hepatectomy).

protect_structure(hepatic_artery, cholecystectomy).

protect_structure(inferior_vena_cava, hepatectomy).

protect_structure(superior_mesenteric_artery, pancreaticoduodenectomy).

protect_structure(superior_mesenteric_vein, pancreaticoduodenectomy).

protect_structure(superior_mesenteric_artery, right_hemicolectomy).

protect_structure(superior_mesenteric_vein, right_hemicolectomy).

protect_structure(portal_vein, gastrectomy).

protect_structure(ureter, colectomy).

protect_structure(ureter, left_hemicolectomy).

protect_structure(ureter, sigmoid_colectomy).

protect_structure(ureter, low_anterior_resection).

protect_structure(ureter, abdominoperineal_resection).

protect_structure(superior_hypogastric_plexus, low_anterior_resection).

protect_structure(inferior_hypogastric_plexus, low_anterior_resection).

protect_structure(inferior_hypogastric_plexus, abdominoperineal_resection).

protect_structure(gonadal_vessels, colectomy).

protect_structure(recurrent_laryngeal_nerve, thyroidectomy).

protect_structure(recurrent_laryngeal_nerve, parathyroidectomy).

protect_structure(external_laryngeal_nerve, thyroidectomy).

protect_structure(parathyroid_glands, thyroidectomy).

protect_structure(thoracic_duct, neck_dissection).

protect_structure(splenic_hilum_vessels, splenectomy).

protect_structure(splenic_vein, distal_pancreatectomy).

protect_structure(tail_of_pancreas, splenectomy).

protect_structure(ilioinguinal_nerve, inguinal_hernia_repair).

protect_structure(iliohypogastric_nerve, inguinal_hernia_repair).

protect_structure(genitofemoral_nerve, inguinal_hernia_repair).

protect_structure(vas_deferens, inguinal_hernia_repair).

protect_structure(femoral_vein, femoral_hernia_repair).

protect_structure(femoral_artery, femoral_hernia_repair).

protect_structure(thoracic_duct, oesophagectomy).

protect_structure(left_recurrent_laryngeal_nerve, oesophagectomy).

protect_structure(trachea, oesophagectomy).

protect_structure(azygos_vein, oesophagectomy).

clamp_allowed(cystic_duct, cholecystectomy).

clamp_allowed(cystic_artery, cholecystectomy).

clamp_allowed(left_hepatic_duct, hepatectomy).

clamp_allowed(right_hepatic_duct, hepatectomy).

must_precede(informed_consent, skin_incision, any_procedure).

must_precede(instrument_count, close_abdomen, any_procedure).

must_precede(swab_count, close_abdomen, any_procedure).

must_precede(achieve_haemostasis, close_abdomen, any_procedure).

must_precede(label_specimen, dispatch_to_pathology, any_procedure).

must_precede(resection, anastomosis, any_procedure).

must_precede(patient_positioning, skin_preparation, any_procedure).

must_precede(skin_preparation, draping, any_procedure).

must_precede(draping, skin_incision, any_procedure).

must_precede(dissect_calot_triangle, divide_cystic_duct, cholecystectomy).

must_precede(dissect_calot_triangle, clip_cystic_duct, cholecystectomy).

must_precede(clip_cystic_duct, divide_cystic_duct, cholecystectomy).

must_precede(clip_cystic_artery, divide_cystic_artery, cholecystectomy).

must_precede(critical_view_safety, divide_cystic_duct, cholecystectomy).

must_precede(retrieve_specimen, remove_ports, laparoscopic_procedure).

must_precede(diagnostic_laparoscopy, major_dissection, laparoscopic_procedure).

must_precede(bowel_preparation, colonic_anastomosis, elective_colectomy).

must_precede(proximal_bowel_division, anastomosis, colectomy).

must_precede(distal_bowel_division, anastomosis, colectomy).

must_precede(air_leak_test, close_abdomen, low_anterior_resection).

must_precede(assess_resectability, resection, pancreaticoduodenectomy).

must_precede(portal_vein_dissection, pancreatic_neck_division, pancreaticoduodenectomy).

must_precede(intraoperative_ultrasound, parenchymal_division, hepatectomy).

must_precede(parenchymal_division, divide_hepatic_vein, hepatectomy).

must_precede(identify_recurrent_laryngeal_nerve, divide_thyroid, thyroidectomy).

must_precede(identify_parathyroid, divide_inferior_thyroid, thyroidectomy).

must_precede(gastric_conduit_preparation, oesophagogastric_anastomosis, oesophagectomy).

must_precede(lymphadenectomy, specimen_retrieval, oesophagectomy).

anastomosis_requirement(tension_free, any_anastomosis).

anastomosis_requirement(adequate_blood_supply, any_anastomosis).

anastomosis_requirement(no_distal_obstruction, any_anastomosis).

anastomosis_requirement(mucosa_to_mucosa_apposition, any_anastomosis).

anastomosis_requirement(water_tight_closure, any_anastomosis).

anastomosis_requirement(check_afferent_loop_orientation, billroth_ii).

anastomosis_requirement(antiperistaltic_check, billroth_ii).

anastomosis_requirement(roux_limb_length_75cm, roux_en_y).

anastomosis_requirement(pancreatic_duct_stented, pancreaticojejunostomy).

anastomosis_requirement(hepaticojejunostomy_stented, pancreaticoduodenectomy).

anastomosis_requirement(donut_check, stapled_colorectal_anastomosis).

anastomosis_test(air_leak_test, colorectal_anastomosis).

anastomosis_test(air_leak_test, low_anterior_resection_anastomosis).

anastomosis_test(water_soluble_contrast, oesophageal_anastomosis).

anastomosis_test(methylene_blue_test, biliary_anastomosis).

anastomosis_test(patency_check, hepaticojejunostomy).

anastomosis_technique(stapled, colorectal_anastomosis).

anastomosis_technique(handsewn, colorectal_anastomosis).

anastomosis_technique(stapled, oesophagectomy).

anastomosis_technique(handsewn, oesophagectomy).

anastomosis_technique(handsewn, hepaticojejunostomy).

anastomosis_technique(stapled, gastrointestinal_anastomosis).

anastomosis_technique(handsewn, gastrointestinal_anastomosis).

anastomosis_technique(handsewn, pancreaticojejunostomy).

drain_indicated(pancreaticoduodenectomy).

drain_indicated(distal_pancreatectomy).

drain_indicated(hepatectomy).

drain_indicated(oesophagectomy).

drain_indicated(gastrectomy).

drain_indicated(splenectomy).

drain_indicated(low_anterior_resection).

drain_indicated(abdominoperineal_resection).

drain_indicated(thyroidectomy).

drain_indicated(cholecystectomy_with_bile_leak_risk).

drain_mandatory(oesophagectomy).

drain_mandatory(pancreaticoduodenectomy).

drain_location(subhepatic, cholecystectomy_with_bile_leak_risk).

drain_location(subhepatic, hepatectomy).

drain_location(right_paracolic, right_hemicolectomy).

drain_location(pelvis, low_anterior_resection).

drain_location(pelvis, abdominoperineal_resection).

drain_location(bed_of_pancreas, distal_pancreatectomy).

drain_location(near_pancreatic_duct, pancreaticoduodenectomy).

drain_location(left_subphrenic, splenectomy).

drain_location(thyroid_bed, thyroidectomy).

drain_type(closed_suction, hepatectomy).

drain_type(closed_suction, pancreaticoduodenectomy).

drain_type(closed_suction, splenectomy).

drain_type(corrugated, superficial_wound).

drain_type(nasogastric, oesophagectomy).

drain_removal_criterion(output_less_than_30ml_per_day, general).

drain_removal_criterion(amylase_less_than_3x_normal_day3, pancreatic_drain).

drain_removal_criterion(no_bile_on_day3, biliary_drain).

drain_removal_criterion(resumption_of_diet, pelvic_drain).

complication_risk(anastomotic_leak, low_anterior_resection, high).

complication_risk(anastomotic_leak, oesophagogastric_anastomosis, high).

complication_risk(anastomotic_leak, pancreaticojejunostomy, high).

complication_risk(anastomotic_leak, colonic_anastomosis, moderate).

complication_risk(anastomotic_leak, ileocolic_anastomosis, low).

complication_risk(bile_leak, cholecystectomy, low).

complication_risk(bile_leak, partial_hepatectomy, moderate).

complication_risk(bile_leak, major_hepatectomy, high).

complication_risk(bile_leak, pancreaticoduodenectomy, moderate).

complication_risk(pancreatic_fistula, distal_pancreatectomy, high).

complication_risk(pancreatic_fistula, pancreaticoduodenectomy, high).

complication_risk(post_pancreatectomy_haemorrhage, pancreaticoduodenectomy, high).

complication_risk(wound_infection, clean_elective, low).

complication_risk(wound_infection, clean_contaminated, moderate).

complication_risk(wound_infection, contaminated_field, high).

complication_risk(wound_infection, dirty_infected, high).

complication_risk(intraoperative_haemorrhage, hepatectomy, high).

complication_risk(intraoperative_haemorrhage, splenectomy, moderate).

complication_risk(intraoperative_haemorrhage, pancreaticoduodenectomy, high).

complication_risk(dvt, major_abdominal_surgery, moderate).

complication_risk(dvt, pelvic_surgery, high).

complication_risk(pulmonary_embolism, major_abdominal_surgery, moderate).

complication_risk(pulmonary_complication, oesophagectomy, high).

complication_risk(pulmonary_complication, upper_abdominal_surgery, moderate).

complication_risk(hypocalcaemia, total_thyroidectomy, moderate).

complication_risk(recurrent_laryngeal_nerve_palsy, thyroidectomy, moderate).

complication_risk(recurrent_laryngeal_nerve_palsy, total_thyroidectomy, high).

complication_risk(ileus, colorectal_surgery, moderate).

complication_risk(small_bowel_obstruction, previous_laparotomy, moderate).

risk_factor(obesity, surgical_site_infection).

risk_factor(obesity, anastomotic_leak).

risk_factor(obesity, dvt).

risk_factor(diabetes, surgical_site_infection).

risk_factor(diabetes, anastomotic_leak).

risk_factor(diabetes, wound_dehiscence).

risk_factor(malnutrition, anastomotic_leak).

risk_factor(malnutrition, wound_dehiscence).

risk_factor(malnutrition, surgical_site_infection).

risk_factor(immunosuppression, surgical_site_infection).

risk_factor(immunosuppression, anastomotic_leak).

risk_factor(steroids, wound_dehiscence).

risk_factor(steroids, surgical_site_infection).

risk_factor(smoking, pulmonary_complication).

risk_factor(smoking, surgical_site_infection).

risk_factor(smoking, anastomotic_leak).

risk_factor(hypoalbuminaemia, anastomotic_leak).

risk_factor(emergency_surgery, wound_infection).

risk_factor(emergency_surgery, anastomotic_leak).

risk_factor(prolonged_surgery, dvt).

risk_factor(prolonged_surgery, surgical_site_infection).

risk_factor(ascites, anastomotic_leak).

risk_factor(ascites, wound_dehiscence).

risk_factor(renal_failure, anastomotic_leak).

risk_factor(ischaemia, anastomotic_leak).

risk_factor(tension, anastomotic_leak).

risk_factor(inadequate_blood_supply, anastomotic_leak).

risk_factor(soft_pancreatic_texture, pancreatic_fistula).

risk_factor(small_pancreatic_duct, pancreatic_fistula).

contraindication(laparoscopic_approach, severe_cardiopulmonary_disease).

contraindication(laparoscopic_approach, uncorrected_coagulopathy).

contraindication(laparoscopic_approach, haemodynamic_instability).

contraindication(laparoscopic_approach, suspected_aortic_injury).

contraindication(primary_anastomosis, haemodynamic_instability).

contraindication(primary_anastomosis, faecal_peritonitis).

contraindication(primary_anastomosis, grossly_contaminated_field).

contraindication(splenorrhaphy, haemodynamic_instability_grade4).

contraindication(stoma_reversal, active_pelvic_sepsis).

contraindication(elective_repair, active_infection_at_site).

caution_required(laparoscopic_approach, previous_multiple_laparotomies).

caution_required(laparoscopic_approach, morbid_obesity).

caution_required(laparoscopic_approach, third_trimester_pregnancy).

caution_required(cholecystectomy, uncorrected_coagulopathy).

caution_required(cholecystectomy, severe_acute_cholecystitis_beyond_72h).

caution_required(cholecystectomy, cirrhosis_child_c).

caution_required(cholecystectomy, pregnancy_first_trimester).

recommended(primary_closure, clean_wound).

recommended(primary_closure, clean_contaminated_wound).

recommended(delayed_primary_closure, contaminated_wound).

recommended(open_wound_management, grossly_contaminated_wound).

recommended(negative_pressure_wound_therapy, grossly_contaminated_wound).

intraoperative_goal(normothermia).

intraoperative_goal(vte_prophylaxis).

intraoperative_goal(normoglycaemia).

intraoperative_goal(haemodynamic_stability).

intraoperative_goal(adequate_oxygenation).

intraoperative_goal(urine_output_greater_than_0_5ml_kg_hr).

intraoperative_goal(pain_control).

antibiotic_timing(prophylactic, within_60_minutes_of_incision).

antibiotic_timing(prophylactic_vancomycin, within_120_minutes_of_incision).

antibiotic_timing(prophylactic, repeat_every_4h_if_prolonged).

antibiotic_timing(therapeutic, guided_by_culture_sensitivity).

monitoring_required(continuous_ecg, general_anaesthesia).

monitoring_required(pulse_oximetry, general_anaesthesia).

monitoring_required(arterial_line, major_vascular_case).

monitoring_required(arterial_line, hepatectomy).

monitoring_required(arterial_line, oesophagectomy).

monitoring_required(central_venous_pressure, hepatectomy).

monitoring_required(urinary_catheter, major_abdominal_surgery).

monitoring_required(nasogastric_tube, oesophagectomy).

monitoring_required(temperature_probe, prolonged_surgery).


% SECTION 9: Derived rules

high_risk_procedure(P) :- complication_risk(_, P, high).

requires_icu(oesophagectomy).
requires_icu(pancreaticoduodenectomy).
requires_icu(major_hepatectomy).

enhanced_recovery_eligible(colectomy).
enhanced_recovery_eligible(low_anterior_resection).
enhanced_recovery_eligible(cholecystectomy).
enhanced_recovery_eligible(gastrectomy).

drain_required(P) :- drain_mandatory(P).
drain_required(P) :- drain_indicated(P).

structure_at_risk(S, P) :- protect_structure(S, P).

safe_anastomosis_conditions_met :-
    anastomosis_requirement(tension_free, _),
    anastomosis_requirement(adequate_blood_supply, _),
    anastomosis_requirement(no_distal_obstruction, _).
